### PR TITLE
Complete rewriting and reorganization of Jenkins management

### PR DESCRIPTION
**Pull request by sapetnioc**
Completely rewrite Jenkins wrapper to make it simpler and have only a dependency on `requests` module.

Now it is necessary to have an environment name to use Jenkins. This name will be used to create the main entry in Jenkins (i.e. the Jenkins job). This name can be given with `CASA_ENVIRONMENT` variable (automatically set by casa_distro 3, see ) or declared in `bv_maker.cfg` in `casa_environment` item in `[general]` section.

`bv_maker` can only add Jenkins build results to the main job (I do no know how to remove a build). Therefore, it will add a start report ate the begining, a report for each step and an end report. All these builds are be attached to the main job.

### CODE REVIEW

**Comment by sapetnioc** [comment]
Tests cannot find my new `maker.brainvisa.jenkins` module. Is `bv_maker` supposed to be self content ? In that case I would just copy the module content in `bv_maker` as it was before.

**Comment by denisri** [comment]
`brainvisa-cmake` needs to be built (it has a C++ command `bv_env` for instance), so it does not run directly from sources. Maybe the python part could be modified to work like this but it hasn't been done this way.
However the project is built differently from the others: as it is the build infrastructure itself, it is built during the `configure` step.

**Comment by sapetnioc** [comment]
This is too much for me now. I removed my module and put back the class in `bv_maker`. Tests are passing.

**Comment by ylep** [comment]
> Is `bv_maker` supposed to be self content ?

Yes it is, I guess that’s the reason why it is over 5000 lines...

Maybe we could change that now that we have casa-distrok

**Comment by sapetnioc** [comment]
When we merge this PR, it may make the current tests to fail starting if bv_maker is not able to find a name for casa environment (either in CASA_ENVIRONMENT but it is only set in v3 by casa_distro, or in bv_maker.cfg).

**Comment by denisri** [comment]
> > Is `bv_maker` supposed to be self content ?
> 
> Yes it is, I guess that’s the reason why it is over 5000 lines...
> 
> Maybe we could change that now that we have casa-distro.

No it's actually not self-contained: `bv_maker` imports a number of modules from `brainvisa.maker`. Thus 1. it's not the reason it cannot load a new new module, and 2. it's not the reason why it is over 5000 lines. The reason for that it rather that it has grown out of control when many features were added, as many of our programs ;) We _can_ move much of the code to modules, yes.

**Comment by denisri** [comment]
> Tests cannot find my new `maker.brainvisa.jenkins` module. Is `bv_maker` supposed to be self content ? In that case I would just copy the module content in `bv_maker` as it was before.

But `sys.path` is adjusted in `bv_maker` in order to find the python modules from the executable location, so it should find a new module, either if run from sources (which we don't do normally but it should work), or after a `bv_maker configure` - ujsing a working `bv_maker` which doesn't import a new unconfigured module... But the one in the build tree is a copy so it should not depend on the new module before it is installed.
I assume the new module is `brainvisa.maker.jenkins`, not `maker.brainvisa.jenkins` ;)

**Comment by denisri** [comment]
Just, the `import brainvisa.maker.jenkins` should be located _after_ `sys.path` is modified. In ed1c2d8005a038caae5cb36722b37e4bef94f868 I read (l 53-):
```
from brainvisa.maker.jenkins import BrainVISAJenkins

# [...]

if os.path.exists(sys.argv[0]):
    this_script = sys.argv[0]
else:
    this_script = None
    for p in os.environ.get('PATH', '').split(os.pathsep) + [os.curdir]:
        s = os.path.join(p, sys.argv[0])
        if os.path.exists(s):
            this_script = s
            break
if this_script:
    this_script = os.path.normpath(os.path.abspath(this_script))
    python_modules = os.path.join(
        os.path.dirname(os.path.dirname(this_script)), 'python')
    if os.path.isdir(python_modules):
        sys.path.insert(0, python_modules)

import brainvisa.maker.components_definition
```

**Pull request merged**
