### PR TITLE
Enable running from source tree and support Conda environment

### PR DESCRIPTION
**Pull request by sapetnioc**
There are many changes in this PR, here is a summary of the most important ones:
- Python module `brainvisa.maker` renamed to `brainvisa_cmake`
- brainvisa-cmake can be used from source tree. For this no more compilation or configuration file creation is necessary. Therefore `bv_env` is now in Python instead of C++ and CMake configuration files `*.cmake.in` are now regular `*.cmake` files.
- Try to not run sip-build when no source files have been modified because it is now quite long (at leas with sip 6 shipped with Conda).
- Enable customization of directory where Python packages are installed using `PYTHON_INSTALL_PREFIX` CMake variable (default value is `"python"` for an installation in `<build dir>/python`).
- `project_info.cmake` of a bv_maker component can be located in the `cmake` directory.
- Added Conda specific code in `conda.cmake`. It is called if `CONDA` CMake variable is defined. To date this is done in `bv_maker.cfg`.

### CODE REVIEW

**Comment by denisri** [comment]
Difficult to review so many changes... we have to test, I'll try it when I can.
I just see that you have removed the symlink to the appropriate "python" command in the build tree. This is actually not needed in a conda environment, but in casa-distro this was very handy to avoid mismatches between the "python" command and the build when PYTHON_EXECUTABLE was not set as the default. Well, OK we are now always using python3...

**Comment by denisri** [comment]
Is is required to build a new casa-distro environment from scratch ?
I have tried checking out the `conda` branch, removed some brainvisa-cmake files in my existing build tree, and run `/casa/host/src/development/brainvisa-cmake/master/bin/bv_maker`
It did configure things, but then fails during build because of missing brainvisa-cmake commands. And I see that most brainvisac-cmake commands (`bv_maker`, `bv_sip4make`, `bv_env_test` etc) are not installed/symlinked in `build/bin/`. Only `bv_env` and `bv_unenv` are available there. Is that normal ? Is is required to add the sources `bin/` in the `PATH` ?

**Comment by sapetnioc** [comment]
No, it should not be required. The `bin` directory of brainvisa-cmake sources is supposed to be in the `PATH`. But it may be necessary to run a first `bv_maker` using source path and possibly to leave the container and start it again to have the new `bv_env` taken into account. I was not able to properly test this procedure yet because my development environment was already modified.

**Comment by sapetnioc** [comment]
I first started modifications only for Conda. I decided later to make them compatible with Apptainer. This is why some changes may not be appropriate. But it is easy to tell if we are in a Conda environment or not, therefore I can but back the `python` link conditionally.

**Comment by denisri** [comment]
Ah OK I didn't understand that the source bin was added in the PATH when restarting the container...
Now I could build in a casa-distro container using the conda branch.

**Comment by denisri** [comment]
I have a build tree which was set to use the conda branch to build inside a casa-distro environment, and I notice that in the conda branch, `bv_maker` does not update all symlinks in the build tree:
I have added a new process in morphologist-gpl from another dev environment (a laptop), pushed it, then from the environement above (on my workstation), ran `bv_maker`. The new process was not available in brainvisa, it did not get a symlink in `build/brainvisa/processes/toolboxes/morphologist/...`
I had to switch back to the master branch to have it symlinked.
Is it because the `brainvisa` directory will move (where ? somewhere in `share/` ?) or because things are not finished in the conda branch ?

**Comment by sapetnioc** [comment]
In `conda` branch, the `build/brainvisa` directory was moved in the Python directory. In Singularity this directory is `build/python`, in Conda it is `lib/python-{version}/site-packages`. Therefore, for you, toolboxes are supposed to be in `build/python/brainvisa/toolboxes`.

The `conda` branch is supposed to work but I did not tested it properly with Singularity yet. If new processes are hidden, this is a bug.

**Comment by denisri** [comment]
Oh yes you told me that bu I forgot I the meantime, thanks. And the mistake for me was to use only the `brainvisa-cmake` project on the `conda` branch, I also needed to set `axon` to the `conda` branch, that's why it did not find its stuff.

**Comment by sapetnioc** [comment]
Thanks to you too. I just had exactly the same problem for Axon while rebuilding a Conda environment from scratch for testing the documented procedure. I could not run `brainvisa`. I will force the `conda` branch for Axon in the conda setup.

**Comment by sapetnioc** [comment]
We have to take a merge decision about this branch. It will become too difficult to merge with `master` and I need to do some changes on both branches.

**Comment by sapetnioc** [comment]
I was wrong, the `master` branch was not difficult to merge. To my opinion, this PR can be merged.

**Comment by denisri** [comment]
A new merge has to be done after 51214a56218fa2ee08ff7b3ed06cf2fc37af566c

**Comment by sapetnioc** [comment]
I merged master and I included support to `pyproject.toml` files. I wanted to separate the two but made a mistake during merge and that was too complex for me to go back.

**Pull request merged**
